# Replication and Evaluation {#replication}

This section discusses the attempt to replicate Orben's study along with the assessment of the use of SCA in this study. We begin by introducing the three datasets used, which can all be found through public sources under permission. We then discuss in details the attempt to replicate the study, including the obstacles to overcome during the replication process. 

## Data and Reprocessing

\par Three large-scale social datasets were used in Orben's study: Monitoring the Future (MTF) from the US [cite], Youth Risk and Behavior Survey (YRBS) from the US [cite], and Millennium Cohort Study (MCS) from the United Kingdom [cite]. The three datasets were all survey data obtained from scientific study of the same name, and encompass survey answers from adolescents aged predominately 12-18 in the time period of 2007 to 2016. The datasets provided wide measures of adolescents' psychological well-being and digital technology use. A considerable number of psychology studies in the existing literature were conducted based on the large-scale studies, which provided wide selection of approaches to modeling and analysis based on the specific dataset. In this section, we discuss the background information of the three datasets and the reprocessing of the data obtained from public sources. 
    
### YRBS

\par The Youth Risk Behavior Surveillance was first launched in 1990, and it's a biennial survey of adolescents that reflects a nationally representative sample of students attending secondary schools. Orben's study focused on the data collected during the time period of 2007 to 2015, and the same set of data was obtained through (website name)[cite]. While Orben used data in SPSS format, we were only able to access the data through Microsoft Access. The datasets were extracted and saved under excel format. It was confirmed that same number of observations were included in the obtained dataset as the data used by Orben, 37,402 girls and 37,412 boys from 2007 to 2015. It was also confirmed that all variables used in Orben's study are contained in the obtained dataset. Most of the work in the reprocessing step for YRBS focused on transforming the characteristic values of the variables used by Orben into relative numerical values.  

\par One noticeable obstacle in this reprocessing step was, since the study is conducted anually and is still ongoing, the survey questions and indexings have been updated several times in the recent years. The majority of the variables in the datasets are named after the survey questions indexes, and the recent updates in survey questions result in differences of indices for survey questions between the current survey and surveys conducted prior to 2015. This lead to mismatches between variable names in the incorporated dataset including data from year of 2015 and prior--the one used by Orben--and the variable names in the dataset obtained for this study, including data from the year of 2017 and prior. Careful research and recoding are done to ensure the correct set of variables was used for the replication. 

### MTF

\par Monitoring the Future was first launched in the year of 1975, and it is an annual nationally representative survey of approximately 50,000 US adolescents in grades 8, 10 and 12. Surveys on adolescents in grade 12 were not used in the analysis since "many of the key items of interest cannot be correlated in their survey". Orben focused on the data collected during the time period of 2008 to 2016, which included 136,190 girls and 132,482 boys. The data are publicly accessible. In Orben's study, a merged dataset containing MTF data from 2008 to 2016 was used. While the MTF data for each year is publicly accessible, no access to a merged MTF dataset for the specified time period have been found. During the time period of 2008 to 2016, the survey has been updated multiple times, along with one major change in data file format after RStudio's release in the year of 2011. Due to the frequent updates in the annual surveys and changes in data files, the variable names vary greatly among the available datasets. This bring excessive difficulties to obtain the exact same dataset as used in Orben's study for replication purpose. 

### MCS

\par The Millennium Cohort Study follows a specific cohort of children born between September 2000 and January 2001 and collects data from both the children and the caregivers. Orben's study focused specifically on the data collected in 2015, when the participated children were aged between 13 and 15. The sample included 5926 girls and 5946 boys along with 10605 caregivers. The same dataset as used by Orben was obtained. The access to the data is open to public but require specific permission. While Orben obtained data in csv format, we were only able to obtain data in SPSS format. The same set of observations, with 5926 girls and 5946 boys borned between September 2000 and January 2001, were included in the dataset, along with the same set of variables as used in Orben's study. 

\par Unlike working with YRBS and MTF, the variable names in the obtained dataset matches well with the variable names in the dataset used by Orben. However, instead of using numerical indices to represent survey answers, in the dataset obtained, the variable values were all in characters with the specific content refering to the specific survey answer. After careful reprocessing, all variable values were transformed into the exact numerical indices matching with the variables values as were in Orben's study. However, two variables--one related to family incomes and one related to siblings--had only NA values in the obtained dataset. The omissions might be done for confidential purpose. The two variables were used as control variables in Orben's study. As we fail to obtain the two variables, they were removed for this attempt to replication. 

## Replication

\par After obtainning the datasets we began the replication of Orben's study. The replication consists of two parts, the replication of a single SCA analysis for each dataset, and the replication of the SCA permutation test, which was used by Orben to assess the significance of the single SCA result. In the following section we discuss the procedure, obstacles and the specific resolutions to the obstacles of replicating the analysis. 

### SCA

\par The first part of the replication is to replicate the single SCA analysis for each dataset. All the replications in this section were done mostly by the original code provided by Orben in the public github repository. Due to the necessary reprocessings mentioned in the previous sections, slight modifications were made to the original code for the replication to be done smoothly. 

\par It is important to understand what Orben considers as a "specification" and how a specification is identified in this study. **(Include a "definition" of specification here)** In this case, the model is set to be a linear regression, with a response variable representing "adolescent mental well-being" and an independent variable representing "technology use", with an optional set of other independent variable considered as control variables. An alternative speicification here is an alternative combination of variables to be used in the linear model. For example, one alternative specification may be using the variable "amount of time spent on watching TV in a day" as the independent variable representing "technology use", "number of times thought of suicide" as the dependent variable representing "adolescent mental well-being", and a list of selected variables as control variables, while another alternative specification choose "whether or not you own a personal computer at home" as the independent variable representing "technology use" instead. An identified specification include one identified variable for "technology use", one identified variable for "adolescent mental well-being", and making the decision of whether or not to include control variables in the model (i.e. simple linear regression or multivariate linear regression). The number of specifications determined vary among three datasets, as the number of relevant variables is different in different dataset.

\par Nearly 2.5 trillion alternative specifications were determined for the MCS study. Considering the computational ability, a random subset of 20,004 specifications for the SCA analysis on MCS data was used instead. A seed is not provided by Orben for the random subset, thus we failed to obtain the exact same subset of specification for this SCA analysis. We instead randomly generated our own subset of 20,004 specifications. It is noteworthy that this randomness can result in discrepancy in SCA result. Considering that the random subset has large size, we expect the degree of this discrepancy to be small. And this expectation is confirmed by replication result: while Orben obtained the median coefficient of the independent variable to be $Median(\beta) = -0.032$, our replication obtained $Median(\beta) = -0.0328$.

\par The problem does not exist for the studies YRBS and MTF. There were less variables available in the dataset relating to technology use and adolescent mental well-being. The number of specifications identified in the two studies are in reasonable size, therefore the exact set of specifications were used for the replications. The result matched well with Orben's result. The median coefficient of the independent variable in the YRBS study was found to be $Median(\beta) = -0.035$  in Orben's study. The result obtained in this replication, when rounded to the same digits, is also -0.035. 

\par \textbf{MTF to be discussed}

### Bootstrapping test

\par The next part of the replication is to replicate the inference of the single specification curves for each data. Orben chose to use a bootstrapping test on the median overall point estimate for significance of the result. We will later assess the choice of the inference test and the correctness of the inference. For now, we will focus mainly on replicating the process to conduct the bootstrapping test as Orben did and the attempt to replicate her result. 

\par 500 SCA tests were conducted in Orben's study on bootstrapped samples for each of the three datasets, and the single SCA results were shown to be significant for all three datasets. The code for the bootstrapping test and SCA are all publically available on Orben's github repository [cite]. The initial attempt of the replication was done using the original code. However, due to the large sizes of the three datasets and the great number of loops used in the R code, the replication process becomes computational expensive. A single SCA will take around 8 hours to run, and performing 500 SCA will take nearly 24 weeks. An ARC computer cluster at Oxford was used by Orben to reduce running time, however, no access to such advanced computer is available for this replication. Therefore, instead of using purely the original code, the code for single SCA and bootstrapping distribution of SCA results have been rewritten using parallel running. The running time have been significantly reduced. The dataset YRBS has the least number of observations and specifications, and after the recoding it now takes about 9 hours for a complete boostrapping test with 500 SCA's to be done using a computer with 8 cores. More time will be needed for the other two datasets, as the number of observations and specifications can be much higher in those two cases. A 96-core server is used. \textbf{Detail times should be added later}


## Evaluating Orben's work

The replication of Orben's work allows a better understanding of Orben's approach and procedure. As mentioned in previous chapter, there exists a number of errors in this study in terms of the usage of SCA, including fundamental misunderstanding of the intentionals of the SCA method, inappropriate choice of specifications, and misinterpretation of the SCA results. 


### "one-to-many" mapping from scientific to statistical hypotheses

- Choice of variable for "tech" - different variable different story, different underlying theories
(- Choice of variable for "well-being")

### True SCA inference

- Interpreting the actual numerical value of SCA test statistic? No, this is not how the SCA results should be interpreted. It only shows evidence for the existence of a relationship or not. 

### Bootstrapping? Permutation? 

### Choice of Multi-variate Linear Regression
